name: 🧩 Component Development
description: Create a new component for LiquidiUI
title: "[Component] Add [Component Name]"
labels: ["component", "phase-1"]
projects: ["tuliopc23/1"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Component Development Request
        Use this template to request a new component for the LiquidiUI library.

  - type: input
    id: component-name
    attributes:
      label: Component Name
      description: What is the name of the component?
      placeholder: e.g., RadioGroup, Breadcrumbs, DataTable
    validations:
      required: true

  - type: dropdown
    id: component-type
    attributes:
      label: Component Type
      description: What type of component is this?
      options:
        - Form
        - Navigation
        - Data Display
        - Layout
        - Feedback
        - Utility
        - Overlay
    validations:
      required: true

  - type: dropdown
    id: phase
    attributes:
      label: Development Phase
      description: Which phase does this component belong to?
      options:
        - Phase 1 (0-2mo) - Essential
        - Phase 2 (2-4mo) - Important
        - Phase 3 (4-6mo) - Experimental
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What is the priority level?
      options:
        - P0 - Critical
        - P1 - High
        - P2 - Medium
        - P3 - Low
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Complexity
      description: How complex is this component to implement?
      options:
        - Low (1-2 days)
        - Medium (3-5 days)
        - High (1-2 weeks)
        - Very High (2+ weeks)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Component Description
      description: Describe what this component does and its main features
      placeholder: A detailed description of the component's functionality...
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: List the specific requirements for this component
      placeholder: |
        - Must support keyboard navigation
        - Should have proper ARIA labels
        - Needs responsive design
        - Requires dark/light theme support
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: API Design
      description: Describe the proposed component API
      placeholder: |
        ```tsx
        <RadioGroup value={value} onValueChange={setValue}>
          <RadioGroup.Item value="option1">Option 1</RadioGroup.Item>
          <RadioGroup.Item value="option2">Option 2</RadioGroup.Item>
        </RadioGroup>
        ```

  - type: textarea
    id: radix-integration
    attributes:
      label: Radix UI Integration
      description: How does this integrate with Radix UI primitives?
      placeholder: Uses @radix-ui/react-radio-group as the base primitive...

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List any dependencies or blockers
      placeholder: |
        - Depends on Portal component (#123)
        - Requires focus management utilities
        - Blocked by design token updates

  - type: checkboxes
    id: checklist
    attributes:
      label: Implementation Checklist
      description: Tasks to complete for this component
      options:
        - label: Component implementation
        - label: TypeScript definitions
        - label: Storybook stories
        - label: Unit tests
        - label: Accessibility tests
        - label: Visual regression tests
        - label: Documentation
        - label: Usage examples
        - label: Performance optimization
        - label: Mobile responsiveness
        - label: Dark/light theme support
        - label: Animation implementation
        - label: Code review
        - label: QA testing

  - type: markdown
    attributes:
      value: |
        ---
        
        **Note:** This issue will be automatically assigned to the appropriate milestone based on the selected phase. Please ensure all requirements are clearly defined before starting implementation.
